services:
  fiberhome_exporter:
    image: mcbyteit/fiberhome_exporter:latest
    container_name: fiberhome_exporter
    environment:
      ROUTER_IP: 'http://192.168.1.1'
      ROUTER_USERNAME: 'admin'
      ROUTER_PASSWORD: 'admin1234'
    ports:
      - 6145:6145
    volumes:
      - ./logs:/logs
    restart: unless-stopped