version: "3"

services:
  fiberhome_exporter:
    image: fiberhome_exporter:latest
    environment:
      HOSTNAME: 'http://192.168.1.1'
      USERNAME: 'admin'
      PASSWORD: 'admin1234'
    ports:
      - 6145:6145
    restart: unless-stopped